cohere_api_key = "q4VnRDJvMnZPudlByBX4XxrczbDE7bM3vELqLbHO"
supabase_url = "https://pkicjdcisyvkbkrrprdn.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBraWNqZGNpc3l2a2JrcnJwcmRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NDA4MTQsImV4cCI6MjA2OTIxNjgxNH0.XXGlA_t7cQVDHtpJJvQEoxTxjpVzO_zMv7qyXlEVPFg"










